retargeting:
  type: vector
  urdf_path: /home/yilin/dataset/robot_description/a1arm_description/urdf/a1arm.urdf 

  # Target refers to the retargeting target, which is the robot hand
  target_joint_names: [ "gripper1_axis" ] # 不包含mimic关节
  target_origin_link_names: [ "gripper1" ]
  target_task_link_names: [ "gripper2" ]
  scaling_factor: 1.

  # Source refers to the retargeting input, which usually corresponds to the human hand
  # The joint indices of human hand joint which corresponds to each link in the target_link_names
  target_link_human_indices: [ [ 8 ], [ 4 ] ]

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2